# Generated by Django 5.0.2 on 2025-07-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='availability',
            field=models.CharField(default='available', max_length=100),
        ),
    ]
