# Generated by Django 5.0.2 on 2025-07-20 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 20, 1, 16, 59, 407574, tzinfo=datetime.timezone.utc)),
        ),
    ]
