# Generated by Django 5.0.2 on 2025-07-21 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectfile_options_projectfile_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 21, 7, 18, 57, 298619, tzinfo=datetime.timezone.utc)),
        ),
    ]
