# Generated by Django 5.0.2 on 2025-07-21 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 21, 8, 42, 35, 328502, tzinfo=datetime.timezone.utc)),
        ),
    ]
