# Generated by Django 5.0.2 on 2025-07-21 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 21, 8, 55, 24, 439223, tzinfo=datetime.timezone.utc)),
        ),
    ]
