# Generated by Django 5.0.2 on 2025-07-22 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_project_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 22, 7, 18, 59, 154311, tzinfo=datetime.timezone.utc)),
        ),
    ]
