# Generated by Django 5.0.2 on 2025-07-23 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_project_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 2, 21, 57, 206737, tzinfo=datetime.timezone.utc)),
        ),
    ]
