# Generated by Django 5.0.2 on 2025-07-25 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_project_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 6, 44, 23, 312495, tzinfo=datetime.timezone.utc)),
        ),
    ]
