# Generated by Django 5.0.2 on 2025-07-26 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_project_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 3, 29, 46, 552135, tzinfo=datetime.timezone.utc)),
        ),
    ]
