# Generated by Django 5.0.2 on 2025-07-30 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_project_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 0, 16, 46, 283777, tzinfo=datetime.timezone.utc)),
        ),
    ]
