# Generated by Django 5.0.2 on 2025-07-31 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_alter_project_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 17, 957621, tzinfo=datetime.timezone.utc)),
        ),
    ]
