# Generated by Django 5.0.2 on 2025-07-31 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_alter_project_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 7, 59, 55, 670322, tzinfo=datetime.timezone.utc)),
        ),
    ]
