# Generated by Django 5.0.2 on 2025-08-12 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_alter_project_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 8, 57, 49, 96471, tzinfo=datetime.timezone.utc)),
        ),
    ]
