# Generated by Django 5.2.5 on 2025-08-16 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0032_alter_project_last_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="last_modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
