# Generated by Django 5.0.2 on 2025-07-22 07:18

import assessment.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weight', models.PositiveIntegerField(help_text='Percentage weight for this assessment')),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentDetailFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for this file (e.g., 'Assignment Guidelines')", max_length=255)),
                ('file', models.FileField(upload_to=assessment.models.assignment_detail_upload_path)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_files', to='assessment.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSampleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for this file (e.g., 'Sample Report')", max_length=255)),
                ('file', models.FileField(upload_to=assessment.models.sample_file_upload_path)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_files', to='assessment.assessment')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessment.assessmentschema'),
        ),
    ]
