# Generated by Django 5.0.2 on 2025-07-22 08:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_application_group_and_more'),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_submissions/')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment')),
            ],
        ),
    ]
