# Generated by Django 5.0.2 on 2025-07-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_studentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='submission_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group')], default='Group', max_length=50),
            preserve_default=False,
        ),
    ]
