# Generated by Django 5.0.2 on 2025-07-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_alter_submissionfile_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='feedback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='grades_received',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
