# Generated by Django 5.0.2 on 2025-07-30 00:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_studentsubmission_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='submit_by',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
