# Generated by Django 5.0.2 on 2025-07-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_assessment_submit_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='published_status',
            field=models.CharField(default='unpublished', max_length=50),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='submission_status',
            field=models.CharField(default='On time', max_length=50),
        ),
    ]
