# Generated by Django 5.0.2 on 2025-07-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_studentsubmission_published_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubmission',
            name='submission_status',
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
