# Generated by Django 5.2.5 on 2025-08-16 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_contact_user_created_at_user_date_of_birth_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admin",
        ),
    ]
