# Generated by Django 5.0.2 on 2025-08-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_contact_user_created_at_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
