# Generated by Django 5.0.2 on 2025-07-21 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='group',
        ),
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.CreateModel(
            name='ApplicationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='application.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ApplicationGroup',
        ),
    ]
